name: Тестирование

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest', 'windows-latest', 'macos-latest', 'macos-13']
        oscript_version: ['stable', 'dev']
    uses: autumn-library/workflows/.github/workflows/test.yml@main
    with:
      oscript_version: ${{ matrix.oscript_version }}