name: Тестирование

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        oscript_version: ['stable', 'dev']
    uses: autumn-library/workflows/.github/workflows/test.yml@main
    with:
      os_versions: '["ubuntu-latest", "windows-2025", "windows-2022", "macos-15", "macos-13"]'
      oscript_version: ${{ matrix.oscript_version }}